### PR TITLE
Support apiPrefix and personal access token in the obsidian plugin

### PR DESCRIPTION
**Pull request by ThePlenkov**

### CODE REVIEW

**Comment by ThePlenkov** [comment]
> Thank you for your submission! Like many open source projects, we ask that you sign our [CLA (Contributor License Agreement)](https://opensource.atlassian.com/cla) before we can accept your contribution. **If your email is listed below**, please ensure that you sign the CLA with the **same email address**. **The following users still need to sign our CLA:**❌ThePlenkov
> 
> Already signed the CLA? To re-check, try refreshing the page.

Cannot sign by some reason. Asked Atlassian for help:
image

**Comment by gorakong** [comment]
helloo @ThePlenkov, looks like it was a dropped webhook. We've delivered the webhook and the check is now passing. You can safely disregard the CLA-Bot's comment :)

**Comment by andymac4182** [comment]
@ThePlenkov Can you jump on Discord to discuss. https://discord.com/invite/3ZVEc3S48x
I am happy to accept a PR that adds support for On premise instances but just doing this work won't enable this to work as on premise API doesn't accept ADF so will need to support translation to Storage format when talking to the API.

**Comment by ThePlenkov** [comment]
@andymac4182 I've prepared a small gist showing how I convert MD to CXHTML using atlaskit:
https://gist.github.com/ThePlenkov/f800bc78cb33fc489d457ab8a4751413

**Pull request closed without merging**
